const data = [
  {
    usecases: { completed: 3, required: 7 },
    tester: { id: 1, name: "Pippo", surname: "Franco" },
    bugs: { critical: 1, high: 3, medium: 10, low: 5 },
    payout: { completion: 10, bug: 15, refund: 0, extra: 0 },
    experience: { completion: 100, extra: 0 },
    note: "Ottimo lavoro",
    status: "pending",
  },
  {
    usecases: { completed: 3, required: 7 },
    tester: { id: 2, name: "Pippo", surname: "Franco" },
    bugs: { critical: 1, high: 3, medium: 10, low: 5 },
    payout: { completion: 10, bug: 15, refund: 0, extra: 0 },
    experience: { completion: 100, extra: 0 },
    note: "Ottimo lavoro",
    status: "pending",
  },
  {
    usecases: { completed: 3, required: 7 },
    tester: { id: 3, name: "Pippo", surname: "Franco" },
    bugs: { critical: 1, high: 3, medium: 10, low: 5 },
    payout: { completion: 10, bug: 15, refund: 0, extra: 0 },
    experience: { completion: 100, extra: 0 },
    note: "Ottimo lavoro",
    status: "pending",
  },
  {
    usecases: { completed: 3, required: 7 },
    tester: { id: 4, name: "Pippo", surname: "Franco" },
    bugs: { critical: 1, high: 3, medium: 10, low: 5 },
    payout: { completion: 10, bug: 15, refund: 0, extra: 0 },
    experience: { completion: 100, extra: 0 },
    note: "Ottimo lavoro",
    status: "pending",
  },
  {
    usecases: { completed: 3, required: 7 },
    tester: { id: 5, name: "Pippo", surname: "Franco" },
    bugs: { critical: 1, high: 3, medium: 10, low: 5 },
    payout: { completion: 10, bug: 15, refund: 0, extra: 0 },
    experience: { completion: 100, extra: 0 },
    note: "Ottimo lavoro",
    status: "pending",
  },
  {
    usecases: { completed: 3, required: 7 },
    tester: { id: 6, name: "Pippo", surname: "Franco" },
    bugs: { critical: 1, high: 3, medium: 10, low: 5 },
    payout: { completion: 10, bug: 15, refund: 0, extra: 0 },
    experience: { completion: 100, extra: 0 },
    note: "Ottimo lavoro",
    status: "pending",
  },
  {
    usecases: { completed: 3, required: 7 },
    tester: { id: 7, name: "Pippo", surname: "Franco" },
    bugs: { critical: 1, high: 3, medium: 10, low: 5 },
    payout: { completion: 10, bug: 15, refund: 0, extra: 0 },
    experience: { completion: 100, extra: 0 },
    note: "Ottimo lavoro",
    status: "pending",
  },
  {
    usecases: { completed: 3, required: 7 },
    tester: { id: 8, name: "Pippo", surname: "Franco" },
    bugs: { critical: 1, high: 3, medium: 10, low: 5 },
    payout: { completion: 10, bug: 15, refund: 0, extra: 0 },
    experience: { completion: 100, extra: 0 },
    note: "Ottimo lavoro",
    status: "pending",
  },
  {
    usecases: { completed: 3, required: 7 },
    tester: { id: 9, name: "Pippo", surname: "Franco" },
    bugs: { critical: 1, high: 3, medium: 10, low: 5 },
    payout: { completion: 10, bug: 15, refund: 0, extra: 0 },
    experience: { completion: 100, extra: 0 },
    note: "Ottimo lavoro",
    status: "pending",
  },
  {
    usecases: { completed: 3, required: 7 },
    tester: { id: 10, name: "Pippo", surname: "Franco" },
    bugs: { critical: 1, high: 3, medium: 10, low: 5 },
    payout: { completion: 10, bug: 15, refund: 0, extra: 0 },
    experience: { completion: 100, extra: 0 },
    note: "Ottimo lavoro",
    status: "pending",
  },
  {
    usecases: { completed: 3, required: 7 },
    tester: { id: 11, name: "Pippo", surname: "Franco" },
    bugs: { critical: 1, high: 3, medium: 10, low: 5 },
    payout: { completion: 10, bug: 15, refund: 0, extra: 0 },
    experience: { completion: 100, extra: 0 },
    note: "Ottimo lavoro",
    status: "pending",
  },
  {
    usecases: { completed: 3, required: 7 },
    tester: { id: 12, name: "Pippo", surname: "Franco" },
    bugs: { critical: 1, high: 3, medium: 10, low: 5 },
    payout: { completion: 10, bug: 15, refund: 0, extra: 0 },
    experience: { completion: 100, extra: 0 },
    note: "Ottimo lavoro",
    status: "pending",
  },
  {
    usecases: { completed: 3, required: 7 },
    tester: { id: 13, name: "Pippo", surname: "Franco" },
    bugs: { critical: 1, high: 3, medium: 10, low: 5 },
    payout: { completion: 10, bug: 15, refund: 0, extra: 0 },
    experience: { completion: 100, extra: 0 },
    note: "Ottimo lavoro",
    status: "pending",
  },
];

export default data;
